# guard 'sass',
# 	:load_paths => ['../assets/stylesheets'],
#   # :debug_info => true,
#   :input => 'scss',
#   :output => 'css'

guard 'sass', :load_paths => ['../assets/stylesheets'], :output => 'css' do
  # :debug_info => true,
  watch(%r{scss/icons\.(scss)})
end

guard 'livereload' do
  # watch(%r{../assets/stylesheets/.+\.(scss)})
  watch(%r{grid/.+\.(html)})
  watch(%r{scss/.+\.(scss)})
end
