source :rubygems

gem 'rack-livereload', :git => 'git@github.com:tyom/rack-livereload.git'
gem 'middleman', '~>3.1.1'
gem 'middleman-livereload', '~>3.1.0'
gem 'middleman-deploy', '~>0.0.12'
gem 'pry'
