guard 'sass',
	:load_paths => ['../assets/stylesheets'],
  :input => 'scss',
  :output => 'css',
  :debug_info => true

guard 'livereload' do
  # watch(%r{../assets/stylesheets/.+\.(scss)})
  watch(%r{.+\.(html)})
  watch(%r{scss/.+\.(scss)})
end
